version: 2
updates:
- package-ecosystem: composer
  directory: "/"
  schedule:
    interval: daily
    time: "09:00"
    timezone: America/New_York
  open-pull-requests-limit: 10
  reviewers:
  - zoiosilva
  assignees:
  - zoiosilva
  allow:
  - dependency-type: direct
  - dependency-type: indirect
  ignore:
  - dependency-name: drupal/core-recommended
    versions:
    - 9.1.6
  - dependency-name: drupal/core-composer-scaffold
    versions:
    - 9.1.6
  - dependency-name: drush/drush
    versions:
    - 10.4.1
    - 10.4.2
  - dependency-name: symfony/filesystem
    versions:
    - 4.4.21
