version: 2
updates:
- package-ecosystem: composer
  directory: "/"
  schedule:
    interval: daily
    # day: tuesday
    time: "07:30"
    timezone: America/Campo_Grande
  open-pull-requests-limit: 15
  assignees:
    - zoiosilva
  labels:
    - "dependabot"
    - "composer update"
  allow:
  - dependency-type: direct
  - dependency-type: indirect
