name: personal-site
recipe: drupal9

config:
  site: personal-site
  php: '8.1'
  composer_version: '2-latest'
  webroot: web
  xdebug: false

# These are tools that are commonly used during development for this template.
tooling:
  drush:
    service: app
