name: personal-site
recipe: drupal9
config:
  webroot: web
  php: '8.2'
  composer_version: 2-latest
  database: mariadb:10.6
  xdebug: false

# services:
#   cache:
#     type: redis:6.0.16
#     persist: true
#     portforward: true

env_file:
  - .lando.env

tooling:
  drush:
    service: appserver
    env:
      DRUSH_OPTIONS_URI: "https://personal-site.lndo.site/"
  drupal:
    service: appserver
    cmd: /app/vendor/bin/drupal
