name: personal-site
recipe: drupal9
config:
  via: nginx
  composer_version: 2-latest
  database: mariadb:10.6
  php: '8.2'
  webroot: web
  xdebug: false

events:
  post-start:
    - appserver: composer install

services:
  appserver:
    overrides:
      environment:
        PHP_IDE_CONFIG: serverName=localhost
        XDEBUG_MODE: debug
        XDEBUG_SESSION: PHPSTORM
      volumes:
        - ${HOME}/.lando/composer_cache:/var/www/.composer
#   cache:
#     type: redis:6.0.16
#     persist: true
#     portforward: true

env_file:
  - .lando.env

tooling:
  xdebug-on:
    service: appserver
    description: Enable xdebug for nginx.
    cmd:
      - rm /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini -f
      - docker-php-ext-enable xdebug
      - pkill -o -USR2 php-fpm
      - echo "Xdebug enabled"
    user: root
  xdebug-off:
    service: appserver
    description: Disable xdebug for nginx.
    cmd:
      - rm /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini -f
      - pkill -o -USR2 php-fpm
      - echo "Xdebug disabled"
    user: root
  xdebug-find-ext-path:
    service: appserver
    description: Find path of xdebug.so file
    cmd:
      - find /usr/local/lib/php/extensions/ -name "xdebug.so"
    user: root
  phpcs:
    service: appserver
    cmd: /app/vendor/bin/phpcs
  phpcbf:
    service: appserver
    cmd: /app/vendor/bin/phpcbf
  drush:
    service: appserver
    env:
      DRUSH_OPTIONS_URI: "https://personal-site.lndo.site/"
