name: Dependabot auto-approve
on:
  pull_request:
    branches:
      - 'dependabot/composer/**'

jobs:
  dependabot:
    runs-on: ubuntu-latest
    if: ${{ contains(github.actor, 'dependabot') }}

    steps:
      - name: Dependabot metadata
        id: metadata
        uses: dependabot/fetch-metadata@v1
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"

      - name: Approve a PR
        run: gh pr review --approve "$PR_URL"
        env:
          PR_URL: ${{ github.event.pull_request.html_url }}
          GH_TOKEN: ${{ github.token }}

      - name: Allow dependabot to merge it
        run: gh pr review --comment --body "@dependabot squash and merge"
        env:
          PR_URL: ${{ github.event.pull_request.html_url }}
          GH_TOKEN: ${{ github.token }}
