name: Dependabot auto-approve

on:
  pull_request:
    paths-ignore:
      - "**/includes/**"
      - "**/libraries/**"
      - "**/node_modules/**"
      - "**/source/**"
      - "**/vendor/**"

jobs:
  dependabot:
    runs-on: ubuntu-latest

    steps:
      - name: Dependabot metadata
        id: metadata
        uses: dependabot/fetch-metadata@v1
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"

      - name: Approve a PR
        run: gh pr review --approve "$PR_URL" --comment --body "@dependabot squash and merge"
        env:
          PR_URL: ${{ github.event.pull_request.html_url }}
          GH_TOKEN: ${{ github.token }}
